---
kind: Secret
apiVersion: v1
metadata:
  name: trextel-tls
  namespace: customer-portal
data:
  tls.crt: >-
    QmFnIEF0dHJpYnV0ZXMKICAgIGxvY2FsS2V5SUQ6IDAxIDAwIDAwIDAwCiAgICBmcmllbmRseU5hbWU6IHdpbGNhcmQtdHJleHRlbC1jb20Kc3ViamVjdD1DTiA9ICoudHJleHRlbC5jb20KCmlzc3Vlcj1DID0gR0IsIFNUID0gR3JlYXRlciBNYW5jaGVzdGVyLCBMID0gU2FsZm9yZCwgTyA9IFNlY3RpZ28gTGltaXRlZCwgQ04gPSBTZWN0aWdvIFJTQSBEb21haW4gVmFsaWRhdGlvbiBTZWN1cmUgU2VydmVyIENBCgotLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJSHB6Q0NCbytnQXdJQkFnSVFhMGkwNmw0K0RBdC9JbjFXc2ZHcnFqQU5CZ2txaGtpRzl3MEJBUXNGQURDQgpqekVMTUFrR0ExVUVCaE1DUjBJeEd6QVpCZ05WQkFnVEVrZHlaV0YwWlhJZ1RXRnVZMmhsYzNSbGNqRVFNQTRHCkExVUVCeE1IVTJGc1ptOXlaREVZTUJZR0ExVUVDaE1QVTJWamRHbG5ieUJNYVcxcGRHVmtNVGN3TlFZRFZRUUQKRXk1VFpXTjBhV2R2SUZKVFFTQkViMjFoYVc0Z1ZtRnNhV1JoZEdsdmJpQlRaV04xY21VZ1UyVnlkbVZ5SUVOQgpNQjRYRFRJd01ESXdOREF3TURBd01Gb1hEVEl5TURVd09EQXdNREF3TUZvd0dERVdNQlFHQTFVRUF3d05LaTUwCmNtVjRkR1ZzTG1OdmJUQ0NBaUl3RFFZSktvWklodmNOQVFFQkJRQURnZ0lQQURDQ0Fnb0NnZ0lCQUtXZnZjTUYKbHpYY1preWYvZkFjZkFVbDQ1UTdySVdTSWxlVExmQXdHM3VOQzB3STg4a3MzbTdsWmtZRHcyREpzUW1jNlB6Wgp6VzM3b2NFUFhLa2pNRENhZ0tweC9pdFUrZ21oTldYaXg3TVR2Y1hqeXVRSW9ib2tzemlyTXVXSnM2REpNa2ZZCmNOMzVOY1NwazRvZWdScmdYbEg0ZUZCVjN6d3dhMEdZT1JxdTVYVm9uSlpaSDFlT0RpMWJlSWdLdTdmcHZaLzkKQkN2bzU1a0luZTdaNEFDRXMzRGthVnJJeGtabGZWcURuaW43ZWY1MC9mVXphV2dpM3BKQlEzYUUrUG05OXlJbwpqZkFtQ0F0YUJnZHhEdHNDcWlYcmgzU1RtNzZiVUhwenBndkpVR3ViV3lyKzYvMmFSaXBuaXQrL2sxR3lxVVdyCkliWkdiQVY0b09QRzhVUkwremZRelJldisyL2l0THpVQVNqNzhyNHNuajFsa1lzYVc2TFBsOFFaVEFRVmpxMCsKSTdISW5zekw2d2NlVUgwaDdEbHMzVVBiZG83dVJHeHJJSHNLQytqa0VMS1NPVkpJMk40cU1WQlJOaGtVS1gxYgpuQklkZGk3eFhnRmIvYXFjY0JQczNXTUxzYVVEQlp4R2lhajRIb1RvTExSQWdYUE5VbU56TlhGUk9haW1uR05LCkNwZWJCekowdnUwTXBOaUEwOXI5M00reElqbzI2S3lKclpBRkR1TSsrT1hyWC9HcWtXUWpVUlo2ZkVSY0oyeEUKUXdySHRIb0RNYTFoUWQyRWg1UGt1QXNXaHdZOGlXMGZkSmFZU2dyZUsreGgwUUYyemNDV0tTK2l2SGd0VTZYZQpRSDlKaXZLUlVmVGozTkw0VzB2QzRaUTNaR2U5UXB0UVIwTEhBZ01CQUFHamdnTnpNSUlEYnpBZkJnTlZIU01FCkdEQVdnQlNOakY3RVZLMks0WGZwbS9tYkJlRzRBWTFoNFRBZEJnTlZIUTRFRmdRVTlmY2V6SVdpVGZCb25VSnEKK0RNVHBvd3d2cW93RGdZRFZSMFBBUUgvQkFRREFnV2dNQXdHQTFVZEV3RUIvd1FDTUFBd0hRWURWUjBsQkJZdwpGQVlJS3dZQkJRVUhBd0VHQ0NzR0FRVUZCd01DTUVrR0ExVWRJQVJDTUVBd05BWUxLd1lCQkFHeU1RRUNBZ2N3CkpUQWpCZ2dyQmdFRkJRY0NBUllYYUhSMGNITTZMeTl6WldOMGFXZHZMbU52YlM5RFVGTXdDQVlHWjRFTUFRSUIKTUlHRUJnZ3JCZ0VGQlFjQkFRUjRNSFl3VHdZSUt3WUJCUVVITUFLR1EyaDBkSEE2THk5amNuUXVjMlZqZEdsbgpieTVqYjIwdlUyVmpkR2xuYjFKVFFVUnZiV0ZwYmxaaGJHbGtZWFJwYjI1VFpXTjFjbVZUWlhKMlpYSkRRUzVqCmNuUXdJd1lJS3dZQkJRVUhNQUdHRjJoMGRIQTZMeTl2WTNOd0xuTmxZM1JwWjI4dVkyOXRNQ1VHQTFVZEVRUWUKTUJ5Q0RTb3VkSEpsZUhSbGJDNWpiMjJDQzNSeVpYaDBaV3d1WTI5dE1JSUI5UVlLS3dZQkJBSFdlUUlFQWdTQwpBZVVFZ2dIaEFkOEFkZ0JHcFZYcmRmcVJJREMxb29scDlQTjlFU3hCZEw3OVNiaUZxL0w4Y1A1dFJ3QUFBWEFSCmJXbzNBQUFFQXdCSE1FVUNJUUR3VlFHMERmMmtrVmt0cXllQUMwLzkyOW1TNG0vaFFXbU01emxuaG5uTU9RSWcKY25UVStIOFpneThFdnVyNXMwcXIvcGMzT2paQkN0MG1Qd003S0pTaUZtb0FkZ0J2VTNhc01mQXhHZGlaQUtSUgpGZjkzRlJ3UjJRTEJBQ2tHamJJSW1qZlpFd0FBQVhBUmJXb2dBQUFFQXdCSE1FVUNJSDJjQWtCekRMZGxQaGZHCkNtelpjZVJsYTJ0YzMydzdkMm1PV0tPeHNpRlBBaUVBc0FQWklDOFZpY0hBTndPdHpaMlJ6ZGNaVjQzSTlXaUcKRlhwK2l1VGhBNlVBZFFBaVJVVUhXVlVrVnBZL29TL3g5MjJHNENNbVk2M0FTMzlkeG9OY2J1SVBBZ0FBQVhBUgpiV29sQUFBRUF3QkdNRVFDSUdGY3pzcXRFZUptK3VQSmZmUlRIbTN4enk2d0FmdWthZFcrTUtydi9ZdmlBaUEvCkFxalR5QVU5Q1ROeDlSR3lpaXNBLzR4ZEZ1bE1zdmhGbWlsOW5mREwwZ0IyQUZXQjFNSVdrRFlCU3VvTG0xYzgKVS9EQTVEaDRjQ1VJRnkranFoMEhFOU1NQUFBQmNCRnRhZmNBQUFRREFFY3dSUUlnWW5kN0ZId1RkT00xTDZkUApjczlkdlJTZGVpVVdhQ2hhbk9wSklFS3kxcVlDSVFEMzE0WlNrQ0s2UHNXZE1XQ29TUVQva1NWVVhmejF4NzZWCk92dnVlOUUzd1RBTkJna3Foa2lHOXcwQkFRc0ZBQU9DQVFFQXBYcXhzNjlCUWdhV2ZCSExNcTJsRnIwV0c5dGMKU3JFcERkaVVoUlJTSWNVRHVoeHR5Q1RSV09hMDV3RWhUcGNvbUdNVkRjcXVjbUhpM09YZmdhZmtwN3RJZDNnTgpUNUZJZXQzQVJXQ2o5eDJzaTdUcEhnSEY4c2JDUXV0d1lxN2VCVXd4aVpCNUpaQkJGTzl4dDlYbmtqbUhKSWh1ClBCODNNK0xoRGhTOUIzWFFDbGF6b1cwMlB3dUxWVEw5TWRJdldCdGJLQXZOYlZMMytKbmszVmJsMHQrL3ZSK0MKM3p1cHdnNnZSS2wrMGw4RG5XWld1QytwamtyOVM2VWR4QkxLR1FUMnkxSWoxbTBnbzhJTVQ4TnhUb1VUcHhtVQpyWkFGcUhVWVZxVk9JdVYyanEyNnpNQmZ0TTl3VUJkbG1XcTBpZjNHU1Vka2NHOEMrZDE2TDYyaG1BPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQotLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJR0V6Q0NBL3VnQXdJQkFnSVFmVnRSSnJSMnVoSGJkQllMdkZNTnB6QU5CZ2txaGtpRzl3MEJBUXdGQURDQgppREVMTUFrR0ExVUVCaE1DVlZNeEV6QVJCZ05WQkFnVENrNWxkeUJLWlhKelpYa3hGREFTQmdOVkJBY1RDMHBsCmNuTmxlU0JEYVhSNU1SNHdIQVlEVlFRS0V4VlVhR1VnVlZORlVsUlNWVk5VSUU1bGRIZHZjbXN4TGpBc0JnTlYKQkFNVEpWVlRSVkpVY25WemRDQlNVMEVnUTJWeWRHbG1hV05oZEdsdmJpQkJkWFJvYjNKcGRIa3dIaGNOTVRneApNVEF5TURBd01EQXdXaGNOTXpBeE1qTXhNak0xT1RVNVdqQ0JqekVMTUFrR0ExVUVCaE1DUjBJeEd6QVpCZ05WCkJBZ1RFa2R5WldGMFpYSWdUV0Z1WTJobGMzUmxjakVRTUE0R0ExVUVCeE1IVTJGc1ptOXlaREVZTUJZR0ExVUUKQ2hNUFUyVmpkR2xuYnlCTWFXMXBkR1ZrTVRjd05RWURWUVFERXk1VFpXTjBhV2R2SUZKVFFTQkViMjFoYVc0ZwpWbUZzYVdSaGRHbHZiaUJUWldOMWNtVWdVMlZ5ZG1WeUlFTkJNSUlCSWpBTkJna3Foa2lHOXcwQkFRRUZBQU9DCkFROEFNSUlCQ2dLQ0FRRUExbk16MXRjOElOQUEwaGRGdU5ZK0I2SS94MEh1TWpESnNHejk5Si9MRXBnUExUK04KVFFFTWdnOFhmMkl1NmJoSWVmc1dnMDZ0MXpJbGs3Y0h2N2xRUDZsTXcwQXE2VG4vMllIS0h4WXlRZHFBSnJragplb2NnSHVQL0lKbzhsVVJ2aDNVR2tFQzBNcE1XQ1JBSUl6N1MzWWNQYjExUkZHb0thY1ZQQVhKcHo5T1RURzBFCm9LTWJnbjZ4bXJudHhaN0ZOM2lmbWdnMCsxWXVXTVFKRGdaa1c3dzMzUEdmS0dpb1ZyQ1NvMXlmdTRpWUNCc2sKSGFzd2hhNnZzQzZlZXAzQndFSWM0Z0x3NnVCSzB1K1FEclRCUUJid2I0VkNTbVQzcERDZy9yOHVveWRham90WQp1SzNER1JlRVkrMXZWdjJEeTJBMHhIUys1cDNiNGVUbHlneGZGUUlEQVFBQm80SUJiakNDQVdvd0h3WURWUjBqCkJCZ3dGb0FVVTNtL1dxb3JTczlVZ09IWW04Q2Q4cklEWnNzd0hRWURWUjBPQkJZRUZJMk1Yc1JVcllyaGQrbWIKK1pzRjRiZ0JqV0hoTUE0R0ExVWREd0VCL3dRRUF3SUJoakFTQmdOVkhSTUJBZjhFQ0RBR0FRSC9BZ0VBTUIwRwpBMVVkSlFRV01CUUdDQ3NHQVFVRkJ3TUJCZ2dyQmdFRkJRY0RBakFiQmdOVkhTQUVGREFTTUFZR0JGVWRJQUF3CkNBWUdaNEVNQVFJQk1GQUdBMVVkSHdSSk1FY3dSYUJEb0VHR1AyaDBkSEE2THk5amNtd3VkWE5sY25SeWRYTjAKTG1OdmJTOVZVMFZTVkhKMWMzUlNVMEZEWlhKMGFXWnBZMkYwYVc5dVFYVjBhRzl5YVhSNUxtTnliREIyQmdncgpCZ0VGQlFjQkFRUnFNR2d3UHdZSUt3WUJCUVVITUFLR00yaDBkSEE2THk5amNuUXVkWE5sY25SeWRYTjBMbU52CmJTOVZVMFZTVkhKMWMzUlNVMEZCWkdSVWNuVnpkRU5CTG1OeWREQWxCZ2dyQmdFRkJRY3dBWVlaYUhSMGNEb3YKTDI5amMzQXVkWE5sY25SeWRYTjBMbU52YlRBTkJna3Foa2lHOXcwQkFRd0ZBQU9DQWdFQU1yOWh2UTVJdzAvSAp1a2ROK0p4NEdRSGNFeDJBYi96RGNMUlNtakV6bWxkUyt6R2VhNlR2VktxSmpVQVhhUGdSRUh6U3lySHhWWWJICjdyTTJrWWIyT1ZHL1JyOFBvTHEwOTM1SnhDbzJGNTdrYURsNnI1Uk9WbSt5ZXp1L0NvYTl6Y1YzSEFPNE9MR2kKSDE5KzI0cmNSa2kyYUFyUHNyVzA0alRrWjZrNFpnbGUwcmo4blNnNkYwQW53bkpPS2YwaFBIelBFL3VXTE1VeApSUDBUN2RXYnFXbG9kM3p1NGYraytUWTRDRk01b29RMG5Cbnp2ZzZzMVNRMzZ5T29lTkRUNSsrU1IyUmlPU0x2Cnh2Y1J2aUtGeG1aRUpDYU9FREtOeUpPdUI1NkRQaS9aK2ZWR2ptTyt3ZWEwM0tiTklhaUdDcFhaTG9VbUd2MzgKc2JaWFFtMlYwVFAyT1JRR2drRTQ5WTlZM0lCYnBOVjlsWGo5cDV2Ly9jV29hYXNtNTZla0JZZGJxYmU0b3lBTApsNmxGaGQyemkrV0pONDRwRGZ3R0YvWTRRQTVDNUJJRyszdnp4aEZvWXQvam1QUVQyQlZQaTdGcDJSQmd2R1FxCjZqRzM1TFdqT2hTYkp1TUxlLzBDanJhWndUaVhXVGIycUhTaWhyWmU2OFprNnMrZ28vbHVucm90RWJhR21BaFkKTGNtc0pXVHlYblcwT01HdWYxcEdnK3BSeXJieG1SRTFhNlZxZThZQXNPZjR2bVN5cmNqQzhhempVZXFraytCNQp5T0dCUU1rS1crRVNQTUZnS3VPWHdJbEN5cFRQUnBnU2FidVkwTUxURFhKTFIyN2xrOFF5S0dPSFErU3dNajRLCjAwdS9JNXNVS1VFcm1nUWZreTN4eHpsSVBLMWFFbjg9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
  tls.key: >-
    LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlKS0FJQkFBS0NBZ0VBcForOXd3V1hOZHhtVEovOThCeDhCU1hqbER1c2haSWlWNU10OERBYmU0MExUQWp6CnlTemVidVZtUmdQRFlNbXhDWnpvL05uTmJmdWh3UTljcVNNd01KcUFxbkgrSzFUNkNhRTFaZUxIc3hPOXhlUEsKNUFpaHVpU3pPS3N5NVltem9Na3lSOWh3M2ZrMXhLbVRpaDZCR3VCZVVmaDRVRlhmUERCclFaZzVHcTdsZFdpYwpsbGtmVjQ0T0xWdDRpQXE3dCttOW4vMEVLK2pubVFpZDd0bmdBSVN6Y09ScFdzakdSbVY5V29PZUtmdDUvblQ5CjlUTnBhQ0xla2tGRGRvVDQrYjMzSWlpTjhDWUlDMW9HQjNFTzJ3S3FKZXVIZEpPYnZwdFFlbk9tQzhsUWE1dGIKS3Y3ci9acEdLbWVLMzcrVFViS3BSYXNodGtac0JYaWc0OGJ4UkV2N045RE5GNi83YitLMHZOUUJLUHZ5dml5ZQpQV1dSaXhwYm9zK1h4QmxNQkJXT3JUNGpzY2llek12ckJ4NVFmU0hzT1d6ZFE5dDJqdTVFYkdzZ2V3b0w2T1FRCnNwSTVVa2pZM2lveFVGRTJHUlFwZlZ1Y0VoMTJMdkZlQVZ2OXFweHdFK3pkWXd1eHBRTUZuRWFKcVBnZWhPZ3MKdEVDQmM4MVNZM00xY1ZFNXFLYWNZMG9LbDVzSE1uUys3UXlrMklEVDJ2M2N6N0VpT2pib3JJbXRrQVVPNHo3NAo1ZXRmOGFxUlpDTlJGbnA4UkZ3bmJFUkRDc2UwZWdNeHJXRkIzWVNIaytTNEN4YUhCanlKYlI5MGxwaEtDdDRyCjdHSFJBWGJOd0pZcEw2SzhlQzFUcGQ1QWYwbUs4cEZSOU9QYzB2aGJTOExobERka1o3MUNtMUJIUXNjQ0F3RUEKQVFLQ0FnQkpTNzlEN2xaenZKejlMaFRJVFNMSmVISVZxSzc1MGFrbkRuaFhBa00zVXp6N29qNlkraVZaK0dWaAplTXJmSzRNUW1RTTIyd0NodXFsajhmTjAycUM1OGJZZE9DTmVjOVhQcXlzaGN0SWp1d25SNkxSaVpEdUdVRFdNClQ1OVBtN2dGNE9SQ2pWT3R1RnNHTkhHWnYxUXRXN3dDRks3U0JwNnJXVll1Q2pyRFIwRSt5MVA0NldvSWFsSjEKMmpRbUtISFl1elZ5OXhzQWY2cjJ1NnlCQnFTdU5ndmZXd1lRNmlkdEFmOE9ybzZ4VDV3MmN2bnNxSnJ1UGZnMwp5M0FhcEZBMjNjM2ZyUWpialVra0ZPdjBJU0dNNU1uOXpCVC9EMC91YzNlVEtWa0RnRXo1d2gvL2tCOUo5UnMyCkt1cDNpS1dla3kxOEtuYlozcUp4YldmdVJaMkJmN29sUlFYdFFVN0s4d1FMRjhtT3d0V20vYTltWEJGWmpIbGwKYUo2TzJSeTltY0QvblZOTkZRU1ZKZkxudmlwbEVZQjdjOWljVndISDFnVFRsN1VQT3YxYWI1UjlDeUxHV2lpUwpWRDVudFJYTmY4WVVZblB5Sm90REhFRUg4Sll2My95Zi9hN1ZFK21CS3VRSVV6UTQ2QVNkMlBDNXQ1U1h1aDRaCmdzb1pZeWhOdnlmWC94bTdHWUhSQ2preU40QjBjcit6T1pWMGtsYkNQY3FnZ2E3bVVKTnRUNXpMUDYyYjhKbHYKMTFOcitIZUlWc0RHc1orVGhDZnB1RlQxbngyR3JpbVR4UjVsa3FaaEVHUlQxV2tuT1dUK0pFQ0VGQUUzOXArVgpLQXZQN24rZHFhbGJXZDFVMVp3US9ITXo2RW5UcGxKTDFnK2NOWFhRM2VxMHMxY2NDUUtDQVFFQXVOcmZrWHkzCkxzQUJyWmtuZzF0eHpiQ1NGa1ZEQ01rRmk3WG9WNXZPM21HMElGY2RHc2xrSFVqa3p6eHhDeVFKVk5DQW1GcUcKQ1BjNnhYNnlGeDNGdjZiM01zQ29EWlFTaDRUL2lVRE9wZ0h6aTdIbFlNSEtTeEdtS2NJL2dpMFk2cndJNk14bApQaWR3eUhteU1JT0REZE83QTk1cVpwbWwweDNvZ2xBRUpxOTZzTi9WalZCem9SNzZDeVc5NTJJTGNoK1ppTlNHCkEyeVpJTDVmc0IvS0pFbjFkNUtrMlBXL05MY2VVdmpTY2tnSStFRmtXRmpJZ2ZENk5QeXNNK0NiVTlXSzNkclQKQmI0SUZYc1A0MEhzSytlbnFabmhpMllwbE9neWgrVCs4aUYwQU5ZYnBYZnlDeG1uT2FKZy9kMFhwV2hmb3QwUgpsc3I5ZmYzZytEamFZd0tDQVFFQTVWNGEzN3l0Zy9XTUpqTVdkYWJkOCt0YXh3VFF0SXBuS09LWklWVkRGOWQ2CmoxTlIxaW9MWEVsdXdiN3RWL1ZzditZUzZZa0loRllNTzRPdWFFNWhPWlZLK1pxUmFTSmw3QngxMXd5ZzlIcHQKb2hGM3VQZXJCVCtVZnpwOFR4RXZZOVI0OE1nYVZUeHA4Y0JPd0l6dU1MY3VibmszTXA2ZzlzRmJjc3IvY0lVMgpBWHJJNXlSRlMzZGdGb21NV1Z2ZWc4bmozWTFFNHpJNjhzTTZmeFhzcGozcXdvUnhVSG4zQlF0ZklYNnh5S3lNCjBwV0NsUkVxWmhNSFZqOGUwUXIwQVp5WWl0a1FlajhqN0lYaVdqNTRYdzNieXc4NEkrbTFsNWtIazJoK2wySUYKWTdFMkRyb2o4M2c4VXVRc04wdUNYMzM1OUF4TEFvV3MrcW1hUGE4UlRRS0NBUUJnMEtGTy9WYWpjWVJ2ZTBzcQpqUFlwbUZTcXZWUENnaVlaYWdocCtmeDZsQWxXOXNrVGdtNmd0OUMraVJWYmxHQWV2NlRhSm04VXV3ZFk4R1l0Cm5UWTRqaVhodXUxSlQwZjFHajhMajVtcmNGSXgwOVlpdXR4TVBNNGVDTkppUjJSSmJIbnVFejdqTXB6ckluR2sKM3Z3QWZlZnd1c2hYUEJtUlhKU3R5MktoTUQ2OTdEMVlhYzVsa0dlODl1TmpFQUtXbnQ0MnY3Z0FpeHdYL2h6MwpqVzY5V3M3bzlUREpRTXdIdS9CeDNFZTcrdVpYdjBmaXpYMFdNVE9hRk12THo5TUtNVWt0c0xIY3pBNUgwZEFjCllpWmpTRXlUa3ppQlhkeGhWTXRDU1RrTmIxL21JRDBTaUtPSUZNTjBlQXI4YXBNNzJsSmNaaFFVT2ZSUnpHbkwKRjF1cEFvSUJBUUNSWm1OdzI4Ry9Pa1I2M3IzcEhUdnNhWkVsUXFjdkcrR2phR29jV0ZsczNyc2g2bmFoWmd2SAptQUZ2THFKMHRPOFlnemdQOVQrQjdLNWFkL0p5eXVVVlJNKy9oVDJTd1N5TlRjbGg1dTZOcktLZEw2ZU9pT3BRCkxHcnRjRnpuSG9URkt5Ynp0RllGSElRb3JYaisxUmdWcDduMmJEOFNocjZSVGllemtIMzNqV3FiNjRNNkM2TWwKNE9uM3Y0QktFVlB3aFdZK3gxUVpGbm1KOVRxNjMySWlUSFBxbFZ6ajREMDRaR29NNkt5NUFyRk91VnFMTnRPQwoyNk0yQ0ZOM3Z4TEpoc1NvbUV1Nnd4WDUxVEdWZGE2R3kxayswMG9LY2hnY252VFBmRmxyaThiUTJNRGsreGpaCk9hbzcvY3NOem44Nkc3ajgvV0g3bWxQNm50TlpNUWF0QW9JQkFFa0xDaHVuOHBqbVFXZHpuc0U4L0N2aEQ4U0kKdXpGMUNUNk51Tkh3K3F4L29veTNNeExUNW1URUNGekZGRHRCRERSQmUwZUc3anB3SkZxMGoyVG1rN1V3WTB1TgpFT1ZDcWVtNzhxOE9maWNMNjV3UDl2ckxRUmpCTTJpNkMzMDl6ZmVzdjJBZXJDQlNQTUp5UDl3KzhrbXJKVERvClY3WWpXMUVtUU51MXBVKzNjdXRPRUpodnV5Z2pEdjYrei80LzA4NVVQMTN1Y2pBRUJ4U0ZyMDV6ZjE5WjJhTVcKbDZuRTdQUGZsM1UwSks1K3J4SUF4SU9WSmFnQ0NUMHE2VlU5ZEdRMHZ4QlZiQVE2b09ENmZxRXhYTm5iUVB6MwpaekFLb0tGRFM2cVpsSHFBblNNSzBQOG9wNFYvcFR2MWYxdUF1WHY2ODlYVHZwUHlGbUFiZnk1dXVkUT0KLS0tLS1FTkQgUlNBIFBSSVZBVEUgS0VZLS0tLS0K
type: kubernetes.io/tls

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: config-overrides-backend
  namespace: customer-portal
data:
  config_overrides.py: |
    DATABASE_URI = 'postgresql://postgres:trextel4190470532!@customer-portal-db-dev.cznsivqvvrxf.us-west-2.rds.amazonaws.com:5432/customer_portal'
    SENTRY_DSN = 'https://c52aa3250e8f4fbb9c19313c76693bcd@sentry.trextel.com/11'
    DRAMATIQ_BROKER_URL = 'redis://redis.postgres:6379/2'

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-portal
  namespace: customer-portal
  labels:
    app: customer-portal
spec:
  selector:
    matchLabels:
      app: customer-portal
  template:
    metadata:
      labels:
        app: customer-portal
    spec:
      volumes:
        - name: config-overrides
          configMap:
            name: config-overrides-backend
            defaultMode: 420
      containers:
        - name: customer-portal
          image: 995135968745.dkr.ecr.us-west-2.amazonaws.com/customer_portal:master
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              protocol: TCP
              name: http
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          resources: { }
          volumeMounts:
            - mountPath: /app/config_overrides.py
              subPath: config_overrides.py
              name: config-overrides
      restartPolicy: Always
      dnsPolicy: ClusterFirst
      schedulerName: default-scheduler

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-portal-dramatiq
  namespace: customer-portal
  labels:
    app: customer-portal-dramatiq
spec:
  selector:
    matchLabels:
      app: customer-portal-dramatiq
  template:
    metadata:
      labels:
        app: customer-portal-dramatiq
    spec:
      volumes:
        - name: config-overrides
          configMap:
            name: config-overrides-backend
            defaultMode: 420
      containers:
        - name: customer-portal-dramatiq
          image: 995135968745.dkr.ecr.us-west-2.amazonaws.com/customer_portal:master
          command:
            - "python"
          args:
            - "app/manage.py"
            - "worker"
          imagePullPolicy: Always
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          resources: { }
          volumeMounts:
            - mountPath: /app/config_overrides.py
              subPath: config_overrides.py
              name: config-overrides
      restartPolicy: Always
      dnsPolicy: ClusterFirst
      schedulerName: default-scheduler

---
apiVersion: v1
kind: Service
metadata:
  name: customer-portal-http
  namespace: customer-portal
spec:
  ports:
    - port: 80
      name: http
      protocol: TCP
      targetPort: 8080
  selector:
    app: customer-portal
  type: ClusterIP
  sessionAffinity: None

---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: "nginx"
  name: customer-portal-ingress
  namespace: customer-portal
spec:
  rules:
    - host: dev.customer-portal.trexup.systems
      http:
        paths:
          - path: /
            backend:
              serviceName: customer-portal-http
              servicePort: 80
  tls:
    - hosts:
        - dev.customer-portal.trexup.systems
      secretName: trextel-tls
